
                                    `Introduction to R Shiny`
                                    
                                    
R Shiny is a package that is used to create dynamic websites with the help of R.
The code snippet below represents the basic structure of an R shiny app.
```{r}
library(shiny)

ui <- fluidPage(
  
)

server <- function(input, output) {
  
}

shinyApp(ui, server)
```
R shiny uses 3 different objects that work with each other to make the page reactive.
  1)Input object/Input List (UI)
  2)Render object           (Server)
  3)Output object           (UI)

```{r}
library(shiny)
countries = c("China","Korea","Japan","India")
ui <- fluidPage(
  sliderInput(inputId = "num", label = "Choose a number", value = 25, min = 1, max = 100),
  textInput(inputId = "Name", label = "Please Enter Your Name",value = ""),
  selectInput(inputId = "hello",choices = countries,label = "Select your Country"),
  textOutput(outputId = "name"),
  verbatimTextOutput(outputId = "Count"),
  plotOutput("hist")
)

server <- function(input, output,session) {
  output$hist <- renderPlot({
    hist(rnorm(input$num))
  })
  output$name = renderText( input$Name)
  output$Count = renderPrint( input$hello)
}

shinyApp(ui = ui, server = server)
```